#lang racket/base
(define (square a) (* a a))
(define (smallest-divisor n) (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))))
(define (divides? a b) (= (remainder b a) 0))

(define (prime? a)
  (= (smallest-divisor a) a))

(define (timed-prime-test n)
  (newline)
  (display n)
  (newline)
  (start-prime-test n (current-inexact-milliseconds)))

(define (start-prime-test n start-time)
  (cond ((prime? n) (report-prime (- (current-inexact-milliseconds) start-time)))))

(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))

(define (search-for-primes a border)
  (timed-prime-test a)
  (cond ((< a border) (search-for-primes (+ a 2) border))))

(search-for-primes 1001 1019)
(newline)
(display "_____________________")
(newline)
(search-for-primes 10001 10037)
(newline)
(display "_____________________")
(newline)
(search-for-primes 100001 100043)
(newline)
(display "_____________________")
(newline)
(search-for-primes 1000001 1000037)